# Generated by Django 4.2.16 on 2024-10-31 09:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        (
            "reservation",
            "0002_alter_reservation_unique_together_reservation_status_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="reservation",
            name="room",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="reservation.room",
            ),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="status",
            field=models.CharField(default="encour", max_length=20),
        ),
        migrations.AlterField(
            model_name="room",
            name="price",
            field=models.CharField(default="", max_length=200),
        ),
    ]
