# Generated by Django 4.2.16 on 2024-11-04 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "reservation",
            "0003_alter_reservation_room_alter_reservation_status_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="room",
            name="image_room",
            field=models.ImageField(default=2, upload_to="", verbose_name="image_Room"),
            preserve_default=False,
        ),
    ]
