# Generated by Django 4.2.16 on 2024-11-05 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reservation", "0004_room_image_room"),
    ]

    operations = [
        migrations.AddField(
            model_name="reservation",
            name="is_delete",
            field=models.BooleanField(default=False),
        ),
    ]
