# Generated by Django 4.2.16 on 2024-11-11 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reservation", "0007_delete_userrequesthistory"),
    ]

    operations = [
        migrations.AlterField(
            model_name="room",
            name="image_room",
            field=models.ImageField(upload_to="images/", verbose_name="image_Room"),
        ),
    ]
