# Generated by Django 4.2.16 on 2024-12-09 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reservation", "0008_alter_room_image_room"),
    ]

    operations = [
        migrations.AlterField(
            model_name="room",
            name="image_room",
            field=models.ImageField(
                blank=True, null=True, upload_to="images/", verbose_name="image_Room"
            ),
        ),
    ]
